[project]
name = "spill-the-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-duckdb>=1.9.0",
    "duckdb>=1.1.3",
    "pandas>=2.2.3",
]
